-- This Source Code Form is subject to the terms of the bCDDL, v. 1.1.
-- If a copy of the bCDDL was not distributed with this
-- file, You can obtain one at http://beamng.com/bCDDL-1.1.txt

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- User constants.
local toolPrefixStr = "Road Spline" -- The global prefix for the road spline tool.
local editModeKey = "roadSplineEditor" -- The edit mode key for this tool.

local minSplineDivisions = 20 -- The minimum number of subdivisions to use for a Road Spline.

local minImportSize = 10.0 -- The minimum size of a Road Spline to import.

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

local M = {}
local logTag = 'roadSplineEditor'

-- Module dependencies.
local buffer = require('string.buffer')
local layerMgr = require('editor/roadSpline/layerMgr')
local geom = require('editor/toolUtilities/geom')
local util = require('editor/toolUtilities/util')
local paint = require('editor/toolUtilities/terrainPainter')

-- Module constants.
local abs, min = math.abs, math.min
local defaultProperties = layerMgr.getSliderDefaults()

-- Module state.
local groups = {}
local groupMap = {}
local tmpPoint2I = Point2I(0, 0)


-- Gets the current road splines array.
local function getGroups() return groups end

-- Gets the group id -> index map.
local function getIdToIdxMap() return groupMap end

-- Gets the prefix string for the tool.
local function getToolPrefixStr() return toolPrefixStr end

-- Gets the edit mode key for the road spline tool.
local function getEditModeKey() return editModeKey end

-- Adds a group to the groups array.
local function addGroupToGroupArray(group)
  -- Ensure we have a unique group name.
  local baseName = group.name or string.format(toolPrefixStr .. " %d", #groups + 1)
  local uniqueName = util.generateUniqueName(baseName, toolPrefixStr)

  -- Create a new folder for the group.
  if not group.sceneTreeFolderId or not scenetree.findObjectById(group.sceneTreeFolderId) then
    local newFolder = createObject("SimGroup")
    local folderNameId = Engine.generateUUID()
    newFolder:registerObject(string.format("%s - %s", uniqueName, folderNameId))
    scenetree.MissionGroup:addObject(newFolder)
    group.sceneTreeFolderId = newFolder:getId()
  end

  -- Add the group to the groups collection.
  table.insert(groups, group)
end

-- Removes the group at the given index.
local function removeGroup(idx)
  local group = groups[idx]
  if group then
    paint.revert(group) -- Revert any terrain painting, if active.
    layerMgr.removeAllLayers(group) -- Remove all layers associated with the group.
    table.clear(group.chunkStartIndices)
    table.clear(group.chunkEndIndices)
    group.numChunks = 0
    if group.sceneTreeFolderId then
      local folder = scenetree.findObjectById(group.sceneTreeFolderId)
      if folder then
        folder:delete() -- Delete the folder associated with the group, if it exists.
      end
    end
    table.remove(groups, idx) -- Remove the group from the groups collection.
  end
  util.computeIdToIdxMap(groups, groupMap) -- Recompute the group id -> index map.
end

-- Removes a linked road spline by ID (called from master spline layer removal).
local function removeLinkedRoadSpline(splineId)
  local idx = groupMap[splineId]
  if idx then
    removeGroup(idx)
  end
end

-- Removes all groups from the session.
local function removeAllGroups(isIncludeDisabled)
  if isIncludeDisabled then
    for i = #groups, 1, -1 do
      local group = groups[i]
      if group then
        removeGroup(i)
      end
    end
    table.clear(groups)
  else
    for i = #groups, 1, -1 do
      local group = groups[i]
      if group.isEnabled and not group.isLink then -- Only remove enabled and unlinked groups.
        removeGroup(i)
      end
    end
  end
end

-- Removes all auto-generated (hidden) layers, then recreates them.
local function recreateAutoGeneratedLayers(group)
  -- Remove all auto-generated layers.
  layerMgr.removeAllHiddenLayers(group)

  -- Recreate the auto-generated decal road layers.
  if group.isLightTreadMarks then layerMgr.addLightTreadMarksLayers(group) end
  if group.isHeavyTreadMarks then layerMgr.addHeavyTreadMarksLayers(group) end
  if group.isRepair1 then layerMgr.addRepair1Layers(group) end
  if group.isRepair2 then layerMgr.addRepair2Layers(group) end
  if group.isDamageAsphalt1 then layerMgr.addRoadDamageAsphalt1Layers(group) end
  if group.isDamageAsphalt2 then layerMgr.addRoadDamageAsphalt2Layers(group) end
  if group.isRoadCrack then layerMgr.addRoadCrackLayers(group) end
  if group.isPatches then layerMgr.addPatchesLayers(group) end
  if group.isRoadCenterLine then layerMgr.addRoadCenterLineLayers(group) end
  if group.isRoadEdgeLines then layerMgr.addRoadEdgeLinesLayers(group) end
  if group.isRoadLaneLines then layerMgr.addRoadLaneLinesLayers(group) end
  if group.isEdgeBlend1 then layerMgr.addEdgeBlend1Layers(group) end
  if group.isEdgeBlend2 then layerMgr.addEdgeBlend2Layers(group) end
  if group.isEdgeBlend3 then layerMgr.addEdgeBlend3Layers(group) end

  -- Mark the group as dirty so the layers get properly updated and rendered
  group.isDirty = true
end

-- Updates the dirty groups.
local function updateDirtyGroups()
  for i = 1, #groups do
    local group = groups[i]
    if group.isDirty then
      -- Check if group has enough nodes to be valid (minimum 2).
      if #group.nodes < 2 then
        -- Remove all layers and clear secondary geometry when insufficient nodes.
        layerMgr.removeAllLayers(group)
        -- Clear secondary geometry arrays
        table.clear(group.ribPoints)
        table.clear(group.divPoints)
        table.clear(group.divWidths)
        table.clear(group.tangents)
        table.clear(group.binormals)
        table.clear(group.normals)
        table.clear(group.discMap)
        table.clear(group.chunkStartIndices)
        table.clear(group.chunkEndIndices)
        group.numChunks = 0
        group.roadLength = 0.0
      else
        paint.revert(group) -- Revert any terrain painting.
        local nodes = group.nodes
        for j = 1, #nodes do
          util.vertRaycast(nodes[j])
        end
        geom.catmullRomRaycast(group, minSplineDivisions) -- Update the secondary (discretised) geometry properties.
        geom.updateRibPointsRaycast(group) -- Update the rib points.

        -- Update the terrain painting, if active.
        if group.isPainting then
          paint.paint(group)
        end

        -- Regenerate auto-generated layers to ensure they cover the current road width.
        recreateAutoGeneratedLayers(group)

        layerMgr.updateAllLayers(group, i) -- Update all the layers.
        groups[i].roadLength = util.getPolyLength(group.nodes)
      end

      groups[i].isDirty = false
    else
      layerMgr.updateOnlyDirtyLayers(group, i) -- The group is not dirty, but it may contain dirty layers.
    end
  end
end

-- Sets the width of the group to a fixed value at every node.
local function setFixedWidth(group, width)
  for i = 1, #group.widths do
    group.widths[i] = width
  end
  group.isDirty = true
end

-- Adds a new group.
local function addNewGroup(name)
  -- Ensure we have a unique group name.
  local baseName = name or string.format(toolPrefixStr .. " %d", #groups + 1)
  local uniqueName = util.generateUniqueName(baseName, toolPrefixStr)
  local id = Engine.generateUUID()

  -- Create a new folder for the group.
  local newFolder = createObject("SimGroup")
  newFolder:registerObject(string.format("%s - %s", uniqueName, id))
  scenetree.MissionGroup:addObject(newFolder)

  -- Create the new group.
  local newGroup = {
    name = uniqueName,
    id = id,
    isLoop = false,
    sceneTreeFolderId = newFolder:getId(),
    isEnabled = true,
    isDirty = false,
    isLink = false,
    linkId = nil,
    roadLength = 0.0,
    nodes = {},
    widths = {},
    nmls = {},
    ribPoints = {},
    divPoints = {},
    divWidths = {},
    tangents = {},
    binormals = {},
    normals = {},
    discMap = {},
    layers = {},
    isOverObjects = false,
    isLightTreadMarks = true,
    isHeavyTreadMarks = false,
    isDamageAsphalt1 = false,
    isDamageAsphalt2 = false,
    isRoadCrack = false,
    isRepair1 = false,
    isRepair2 = false,
    isPatches = false,
    isRoadCenterLine = true,
    isRoadEdgeLines = true,
    isRoadLaneLines = false,
    isEdgeBlend1 = true,
    isEdgeBlend2 = false,
    isEdgeBlend3 = false,

    -- Terrain painting properties.
    isPainting = false,
    paintMargin = 0.0,
    paintMaterialIdx = defaultProperties.defaultPaintMaterialIdx,

    -- Paint data arrays.
    paintedDataX = {},
    paintedDataY = {},
    paintedDataVals = {},
    paintedDataBoxXMin = 0,
    paintedDataBoxXMax = 0,
    paintedDataBoxYMin = 0,
    paintedDataBoxYMax = 0,

    -- Chunk data for long splines.
    chunkStartIndices = {},
    chunkEndIndices = {},
    numChunks = 0,
  }

  -- Create the initial auto-generated (hidden) layers.
  recreateAutoGeneratedLayers(newGroup)

  -- Add the new group to the groups collection.
  table.insert(groups, newGroup)

  -- Recompute the group id -> index map.
  util.computeIdToIdxMap(groups, groupMap)
end

-- Copies the layer profile from the given group (only the layers).
local function copyGroupProfile(sourceGroup)
  local profile = {
    layers = {},
    isOverObjects = sourceGroup.isOverObjects,
    isLightTreadMarks = sourceGroup.isLightTreadMarks,
    isHeavyTreadMarks = sourceGroup.isHeavyTreadMarks,
    isRoadCrack = sourceGroup.isRoadCrack,
    isRepair1 = sourceGroup.isRepair1,
    isRepair2 = sourceGroup.isRepair2,
    isPatches = sourceGroup.isPatches,
    isDamageAsphalt1 = sourceGroup.isDamageAsphalt1,
    isDamageAsphalt2 = sourceGroup.isDamageAsphalt2,
    isRoadCenterLine = sourceGroup.isRoadCenterLine,
    isRoadEdgeLines = sourceGroup.isRoadEdgeLines,
    isRoadLaneLines = sourceGroup.isRoadLaneLines,
    isEdgeBlend1 = sourceGroup.isEdgeBlend1,
    isEdgeBlend2 = sourceGroup.isEdgeBlend2,
    isEdgeBlend3 = sourceGroup.isEdgeBlend3,
  }

  local layers, ctr = sourceGroup.layers, 1
  for i = 1, #layers do
    local layer = layers[i]
    if not layer.isHidden then -- Do not copy any auto-generated layers.
      profile.layers[ctr] = layerMgr.deepCopyLayer(layer)
      ctr = ctr + 1
    end
  end

  return profile
end

-- Pastes a layer profile onto the given group.
local function pasteGroupProfile(targetGroup, profile)
  layerMgr.removeAllLayers(targetGroup)

  for i = 1, #profile.layers do
    targetGroup.layers[i] = layerMgr.deepCopyLayer(profile.layers[i])
  end

  targetGroup.isOverObjects = profile.isOverObjects or false
  targetGroup.isLightTreadMarks = profile.isLightTreadMarks or false
  targetGroup.isHeavyTreadMarks = profile.isHeavyTreadMarks or false
  targetGroup.isRoadCrack = profile.isRoadCrack or false
  targetGroup.isRepair1 = profile.isRepair1 or false
  targetGroup.isRepair2 = profile.isRepair2 or false
  targetGroup.isPatches = profile.isPatches or false
  targetGroup.isDamageAsphalt1 = profile.isDamageAsphalt1 or false
  targetGroup.isDamageAsphalt2 = profile.isDamageAsphalt2 or false
  targetGroup.isRoadCenterLine = profile.isRoadCenterLine or false
  targetGroup.isRoadEdgeLines = profile.isRoadEdgeLines or false
  targetGroup.isRoadLaneLines = profile.isRoadLaneLines or false
  targetGroup.isEdgeBlend1 = profile.isEdgeBlend1 or false
  targetGroup.isEdgeBlend2 = profile.isEdgeBlend2 or false
  targetGroup.isEdgeBlend3 = profile.isEdgeBlend3 or false
  targetGroup.isOverObjects = profile.isOverObjects or false

  targetGroup.isDirty = true

  -- Recreate the auto-generated layers.
  recreateAutoGeneratedLayers(targetGroup)
end

-- Deep copies the given group.
local function deepCopyGroup(group)
  local copy = buffer.decode(buffer.encode(group))
  table.clear(copy.divPoints)
  table.clear(copy.divWidths)
  table.clear(copy.tangents)
  table.clear(copy.binormals)
  table.clear(copy.normals)
  table.clear(copy.discMap)
  return copy
end

-- Deep copies the full group state.
local function deepCopyAllGroups()
  local copy = {}
  for i = 1, #groups do
    copy[i] = deepCopyGroup(groups[i])
  end
  return copy
end

-- Splits the given group at the selected node index.
local function splitGroup(group, groupIdx, selectedNodeIdx)
  -- Revert any terrain painting, if active.
  paint.revert(group)

  if group.isLoop then
    -- Use the helper function for loop spline geometry splitting.
    group.nodes, group.widths, group.nmls = geom.splitLoopSplineGeometry(group.nodes, group.widths, group.nmls, selectedNodeIdx)
    group.isLoop = false
    group.isDirty = true
  else
    local nodes1, widths1, nmls1, nodes2, widths2, nmls2 = geom.splitSplineGeometry(group.nodes, group.widths, group.nmls, selectedNodeIdx)

    -- Prepare copies.
    local group1 = deepCopyGroup(group)
    group1.name = group.name .. " (1)"
    group1.id = Engine.generateUUID()
    group1.nodes = nodes1
    group1.widths = widths1
    group1.nmls = nmls1
    group1.isDirty = true

    local group2 = deepCopyGroup(group)
    group2.name = group.name .. " (2)"
    group2.id = Engine.generateUUID()
    group2.nodes = nodes2
    group2.widths = widths2
    group2.nmls = nmls2
    group2.isDirty = true

    -- Remove the old group and add the new ones.
    removeGroup(groupIdx)
    addGroupToGroupArray(group1)
    addGroupToGroupArray(group2)
  end

  -- Recompute the group id -> index map.
  util.computeIdToIdxMap(groups, groupMap)
end

-- Joins two unlooped road group splines into one, modifying group1 and deleting group2.
local function joinRoadSplines(groupIdx1, nodeIdx1, groupIdx2, nodeIdx2)
  local group1, group2 = groups[groupIdx1], groups[groupIdx2]
  if not group1 or not group2 then
    return
  end

  -- Join the two groups.
  local nodesNew, widthsNew, nmlsNew = geom.joinSplineGeometry(group1.nodes, group1.widths, group1.nmls, nodeIdx1, group2.nodes, group2.widths, group2.nmls, nodeIdx2)
  if not nodesNew then
    return -- Early return if invalid node indices.
  end

  -- Apply joined geometry to group1.
  group1.nodes = nodesNew
  group1.widths = widthsNew
  group1.nmls = nmlsNew
  group1.isLoop = false
  group1.isDirty = true

  -- Remove group2 directly to avoid index shift issues.
  removeGroup(groupIdx2)

  -- Recompute the ID-to-Index map for consistency.
  util.computeIdToIdxMap(groups, groupMap)
end

-- Converts the given paths (traced from a bitmap) to Road Splines.
local function convertPathsToRoadSplines(paths)
  local tb = extensions.editor_terrainEditor.getTerrainBlock()
  local te = extensions.editor_terrainEditor.getTerrainEditor()
  for i = 1, #paths do
    local path = paths[i]

    -- Create a new Road Spline.
    addNewGroup()
    local group = groups[#groups]

    -- Convert the grid points to world space.
    local points = path.points
    local numPoints = #points
    local pointsWS = {}
    for j = 1, numPoints do
      local pointGrid = points[j]
      tmpPoint2I.x, tmpPoint2I.y = pointGrid.x, pointGrid.y
      pointsWS[j] = te:gridToWorldByPoint2I(tmpPoint2I, tb)
    end

    -- If the path is sufficiently large, then import it.
    local aabb = geom.getAABB(pointsWS)
    if min(abs(aabb.xMax - aabb.xMin), abs(aabb.yMax - aabb.yMin)) > minImportSize then
      group.nodes, group.widths = pointsWS, path.widths -- Set the nodes and widths directly.
      for j = 1, numPoints do
        group.nmls[j] = geom.getTerrainNormal(pointsWS[j]) -- Compute the normals for each node.
      end
    end
  end
  log('I', logTag, string.format("Converted %d traced paths to Road Splines. %d paths were too small to import.", #paths, #paths - #groups))
end

-- Serialises a group.
local function serializeGroup(group)
  paint.revert(group) -- Revert any terrain painting, if active.
  table.clear(group.divPoints)
  table.clear(group.divWidths)
  table.clear(group.tangents)
  table.clear(group.binormals)
  table.clear(group.normals)
  table.clear(group.discMap)
  table.clear(group.ribPoints)
  return buffer.encode(group)
end

-- Deserialises a group.
local function deserializeGroup(data, isCreateObject)
  local group = buffer.decode(data)
  group.isDirty = true

  -- Create a new scene tree folder for the road spline, if requested.
  if isCreateObject then
    local newFolder = createObject("SimGroup")
    newFolder:registerObject(string.format("%s - %s", group.name, group.id))
    newFolder.cansave = true
    scenetree.MissionGroup:addObject(newFolder)
    group.sceneTreeFolderId = newFolder:getId()
  end

  return group
end

-- Undo/redo core for single group changes.
local function singleGroupUndoRedoCore(data)
  local idx = groupMap[data.id]
  if idx then
    local group = groups[idx]
    paint.revert(group) -- Revert any terrain painting, if active.
    layerMgr.removeAllLayers(group) -- Remove all layers associated with the group.
    group.layers = layerMgr.deepCopyAllLayers(data.layers) -- Need to deep copy all layers from the undo/redo history.
    group.name = data.name
    group.id = data.id
    group.isLoop = data.isLoop
    group.isDirty = true -- Set the dirty flag to true.
    group.isEnabled = data.isEnabled
    group.isLink = data.isLink
    group.linkId = data.linkId
    group.nodes = data.nodes
    group.widths = data.widths
    group.nmls = data.nmls
    group.roadLength = data.roadLength
    group.isOverObjects = data.isOverObjects
    group.isLightTreadMarks = data.isLightTreadMarks
    group.isHeavyTreadMarks = data.isHeavyTreadMarks
    group.isDamageAsphalt1 = data.isDamageAsphalt1
    group.isDamageAsphalt2 = data.isDamageAsphalt2
    group.isRoadCrack = data.isRoadCrack
    group.isRepair1 = data.isRepair1
    group.isRepair2 = data.isRepair2
    group.isPatches = data.isPatches
    group.isRoadCenterLine = data.isRoadCenterLine
    group.isRoadEdgeLines = data.isRoadEdgeLines
    group.isRoadLaneLines = data.isRoadLaneLines
    group.isEdgeBlend1 = data.isEdgeBlend1
    group.isEdgeBlend2 = data.isEdgeBlend2
    group.isEdgeBlend3 = data.isEdgeBlend3

    -- Terrain painting properties.
    group.isPainting = data.isPainting
    group.paintMargin = data.paintMargin
    group.paintMaterialIdx = data.paintMaterialIdx
    group.paintedDataX = util.fastArrayCopy(data.paintedDataX)
    group.paintedDataY = util.fastArrayCopy(data.paintedDataY)
    group.paintedDataVals = util.fastArrayCopy(data.paintedDataVals)
    group.paintedDataBoxXMin = data.paintedDataBoxXMin
    group.paintedDataBoxXMax = data.paintedDataBoxXMax
    group.paintedDataBoxYMin = data.paintedDataBoxYMin
    group.paintedDataBoxYMax = data.paintedDataBoxYMax

    -- Special case for when the group has been renamed.
    if data.isUpdateSceneTree then
      if group.sceneTreeFolderId then
        local folder = scenetree.findObjectById(group.sceneTreeFolderId)
        if folder then
          folder:setName(group.name)
        end
      end
      editor.refreshSceneTreeWindow()
    end
  end
end

-- Handles the undo/redo for single group edits.
local function singleGroupEditUndo(data) singleGroupUndoRedoCore(data.old) end
local function singleGroupEditRedo(data) singleGroupUndoRedoCore(data.new) end

-- Undo/redo core for trans-group edits.
local function transGroupUndoRedoCore(data)
  paint.revertAll(groups) -- Revert any terrain painting, if active.
  removeAllGroups(true) -- Remove all groups.
  for i = 1, #data do
    addGroupToGroupArray(deepCopyGroup(data[i])) -- Add the given groups.
  end
  util.computeIdToIdxMap(groups, groupMap) -- Recompute the group id -> index map.

  -- Set the isDirty flag for all restored groups to ensure proper updates.
  for i = 1, #groups do
    groups[i].isDirty = true
  end
end

-- Handles the undo/redo for trans-group edits.
local function transGroupEditUndo(groupsData) transGroupUndoRedoCore(groupsData.old) end
local function transGroupEditRedo(groupsData) transGroupUndoRedoCore(groupsData.new) end

-- Returns the current list of Road Splines.
local function getCurrentRoadSplineList()
  local list, ctr = {}, 1
  for i = 1, #groups do
    local group = groups[i]
    if group.isEnabled then
      list[ctr] = { name = group.name, id = group.id, type = toolPrefixStr }
      ctr = ctr + 1
    end
  end
  return list
end

-- Returns true if the given Road Spline is linked, false otherwise.
local function isLinked(id)
  local group = groups[groupMap[id]]
  return group and group.isLink or false
end

-- Sets the given Road Spline to be linked or not.
local function setLink(id, groupId, isLink)
  local group = groups[groupMap[id]]
  if group then
    group.isLink = isLink
    if isLink then
      group.linkId = groupId
    else
      group.linkId = nil
    end
    group.isDirty = true
  end
end

-- Updates the given linked Road Spline with the given geometry.
local function updateLinkedRoadSpline(id, points, widths, nmls, isLoop, isConformToTerrain)
  local group = groups[groupMap[id]]
  if group then
    group.nodes, group.widths, group.nmls = points, widths, nmls
    group.isLoop = isLoop -- Propagate the loop state of the master spline to the linked spline.
    group.isDirty = true
  end
end

-- Unlinks all Road Splines.
local function unlinkAll()
  for i = 1, #groups do
    local group = groups[i]
    if group.isLink then
      group.isLink = false
      group.linkId = nil
    end
    group.isDirty = true
  end
end


-- Public interface.
M.getGroups =                                          getGroups
M.getIdToIdxMap =                                      getIdToIdxMap
M.getToolPrefixStr =                                   getToolPrefixStr
M.getEditModeKey =                                     getEditModeKey
M.addGroupToGroupArray =                               addGroupToGroupArray

M.removeGroup =                                        removeGroup
M.removeLinkedRoadSpline =                             removeLinkedRoadSpline
M.removeAllGroups =                                    removeAllGroups

M.updateDirtyGroups =                                  updateDirtyGroups

M.setFixedWidth =                                      setFixedWidth
M.recreateAutoGeneratedLayers =                        recreateAutoGeneratedLayers

M.addNewGroup =                                        addNewGroup

M.copyGroupProfile =                                   copyGroupProfile
M.pasteGroupProfile =                                  pasteGroupProfile
M.deepCopyGroup =                                      deepCopyGroup
M.deepCopyAllGroups =                                  deepCopyAllGroups

M.splitGroup =                                         splitGroup
M.joinRoadSplines =                                    joinRoadSplines

M.convertPathsToRoadGroups =                           convertPathsToRoadSplines

M.serializeGroup =                                     serializeGroup
M.deserializeGroup =                                   deserializeGroup

M.singleGroupEditUndo =                                singleGroupEditUndo
M.singleGroupEditRedo =                                singleGroupEditRedo
M.transGroupEditUndo =                                 transGroupEditUndo
M.transGroupEditRedo =                                 transGroupEditRedo

M.getCurrentRoadSplineList =                           getCurrentRoadSplineList
M.isLinked =                                           isLinked
M.setLink =                                            setLink
M.updateLinkedRoadSpline =                             updateLinkedRoadSpline
M.unlinkAll =                                          unlinkAll

return M