-- This Source Code Form is subject to the terms of the bCDDL, v. 1.1.
-- If a copy of the bCDDL was not distributed with this
-- file, You can obtain one at http://beamng.com/bCDDL-1.1.txt

local M = {}


-- Headers used with configuration .csv files.
local headers = {
  "Section",
  "Subsection",
  "Parameter Name",
  "Parameter Value",
  "Type",
  "Description",
  "Units",
  "Notes" }

-- Cosimulation group names.
local groups = {
  kinematics = 'Kinematics',
  driver = 'Driver',
  wheels = 'Wheels',
  electrics = 'Electrics',
  powertrain = 'Powertrain',
  idealRADAR = 'Ideal RADAR',
  roadsSensor = 'Roads Sensor' }

-- Cosimulation group property names.
local names = {
  vehiclePositionX = 'vehiclePositionX',                                                            -- Kinematics.
  vehiclePositionY = 'vehiclePositionY',
  vehiclePositionZ = 'vehiclePositionZ',
  vehicleVelocityX = 'vehicleVelocityX',
  vehicleVelocityY = 'vehicleVelocityY',
  vehicleVelocityZ = 'vehicleVelocityZ',
  vehicleAccelerationX = 'vehicleAccelerationX',
  vehicleAccelerationY = 'vehicleAccelerationY',
  vehicleAccelerationZ = 'vehicleAccelerationZ',
  vehicleRoll = 'vehicleRoll',
  vehiclePitch = 'vehiclePitch',
  vehicleYaw = 'vehicleYaw',
  vehicleRollRate = 'vehicleRollRate',
  vehiclePitchRate = 'vehiclePitchRate',
  vehicleYawRate = 'vehicleYawRate',
  vehicleGroundSpeed = 'vehicleGroundSpeed',
  vehicleAltitude = 'vehicleAltitude',
  vehicleForwardX = 'vehicleForwardX',
  vehicleForwardY = 'vehicleForwardY',
  vehicleForwardZ = 'vehicleForwardZ',
  vehicleUpX = 'vehicleUpX',
  vehicleUpY = 'vehicleUpY',
  vehicleUpZ = 'vehicleUpZ',
  vehicleRightX = 'vehicleRightX',
  vehicleRightY = 'vehicleRightY',
  vehicleRightZ = 'vehicleRightZ',
  vehicleInitialLength = 'vehicleInitialLength',
  vehicleInitialWidth = 'vehicleInitialWidth',
  vehicleInitialHeight = 'vehicleInitialHeight',
  vehicleCOGWithWheelsX = 'vehicleCOGWithWheelsX',
  vehicleCOGWithWheelsY = 'vehicleCOGWithWheelsY',
  vehicleCOGWithWheelsZ = 'vehicleCOGWithWheelsZ',
  vehicleCOGWithoutWheelsX = 'vehicleCOGWithoutWheelsX',
  vehicleCOGWithoutWheelsY = 'vehicleCOGWithoutWheelsY',
  vehicleCOGWithoutWheelsZ = 'vehicleCOGWithoutWheelsZ',
  vehicleMidFrontBumperX = 'vehicleMidFrontBumperX',
  vehicleMidFrontBumperY = 'vehicleMidFrontBumperY',
  vehicleMidFrontBumperZ = 'vehicleMidFrontBumperZ',
  vehicleMidRearBumperX = 'vehicleMidRearBumperX',
  vehicleMidRearBumperY = 'vehicleMidRearBumperY',
  vehicleMidRearBumperZ = 'vehicleMidRearBumperZ',
  vehicleFrontAxleMidpointX = 'vehicleFrontAxleMidpointX',
  vehicleFrontAxleMidpointY = 'vehicleFrontAxleMidpointY',
  vehicleFrontAxleMidpointZ = 'vehicleFrontAxleMidpointZ',
  vehicleRearAxleMidpointX = 'vehicleRearAxleMidpointX',
  vehicleRearAxleMidpointY = 'vehicleRearAxleMidpointY',
  vehicleRearAxleMidpointZ = 'vehicleRearAxleMidpointZ',

  throttle = 'throttle',                                                                            -- Driver.
  throttleInput = 'throttleInput',
  brake = 'brake',
  brakeInput = 'brakeInput',
  clutch = 'clutch',
  clutchInput = 'clutchInput',
  parkingBrake = 'parkingBrake',
  parkingBrakeInput = 'parkingBrakeInput',
  steeringWheelPosition = 'steeringWheelPosition',
  steeringWheelPositionInput = 'steeringWheelPositionInput',

  wheelSpeed = 'wheelSpeed',                                                                        -- Wheels.
  angularVelocity = 'angularVelocity',
  downforce = 'downforce',
  brakingTorque = 'brakingTorque',
  propulsionTorque = 'propulsionTorque',
  frictionTorque = 'frictionTorque',
  wheelAngle = 'wheelAngle',

  imuPositionX = 'imuPositionX',                                                                    -- IMU.
  imuPositionY = 'imuPositionY',
  imuPositionZ = 'imuPositionZ',
  imuAxis1DirectionX = 'imuAxis1DirectionX',
  imuAxis1DirectionY = 'imuAxis1DirectionY',
  imuAxis1DirectionZ = 'imuAxis1DirectionZ',
  imuAxis2DirectionX = 'imuAxis2DirectionX',
  imuAxis2DirectionY = 'imuAxis2DirectionY',
  imuAxis2DirectionZ = 'imuAxis2DirectionZ',
  imuAxis3DirectionX = 'imuAxis3DirectionX',
  imuAxis3DirectionY = 'imuAxis3DirectionY',
  imuAxis3DirectionZ = 'imuAxis3DirectionZ',
  imuMass = 'imuMass',
  imuAngularVelocityRawAxis1 = 'imuAngularVelocityRawAxis1',
  imuAngularVelocityRawAxis2 = 'imuAngularVelocityRawAxis2',
  imuAngularVelocityRawAxis3 = 'imuAngularVelocityRawAxis3',
  imuAngularVelocitySmoothedAxis1 = 'imuAngularVelocitySmoothedAxis1',
  imuAngularVelocitySmoothedAxis2 = 'imuAngularVelocitySmoothedAxis2',
  imuAngularVelocitySmoothedAxis3 = 'imuAngularVelocitySmoothedAxis3',
  imuAccelerationRawAxis1 = 'imuAccelerationRawAxis1',
  imuAccelerationRawAxis2 = 'imuAccelerationRawAxis2',
  imuAccelerationRawAxis3 = 'imuAccelerationRawAxis3',
  imuAccelerationSmoothedAxis1 = 'imuAccelerationSmoothedAxis1',
  imuAccelerationSmoothedAxis2 = 'imuAccelerationSmoothedAxis2',
  imuAccelerationSmoothedAxis3 = 'imuAccelerationSmoothedAxis3',
  imuAngularAccelerationAxis1 = 'imuAngularAccelerationAxis1',
  imuAngularAccelerationAxis2 = 'imuAngularAccelerationAxis2',
  imuAngularAccelerationAxis3 = 'imuAngularAccelerationAxis3',
  imuReadingTimestamp = 'imuReadingTimestamp',

  gpsXCoordinate = 'gpsXCoordinate',                                                                -- GPS.
  gpsYCoordinate = 'gpsYCoordinate',
  gpsLongitude = 'gpsLongitude',
  gpsLatitude = 'gpsLatitude',
  gpsReadingTimestamp = 'gpsReadingTimestamp',

  idealRADARVehicle1Distance = 'idealRADARVehicle1Distance',                                        -- Ideal RADAR.
  idealRADARVehicle1Length = 'idealRADARVehicle1Length',
  idealRADARVehicle1Width = 'idealRADARVehicle1Width',
  idealRADARVehicle1VelocityX = 'idealRADARVehicle1VelocityX',
  idealRADARVehicle1VelocityY = 'idealRADARVehicle1VelocityY',
  idealRADARVehicle1VelocityZ = 'idealRADARVehicle1VelocityZ',
  idealRADARVehicle1AccelerationX = 'idealRADARVehicle1AccelerationX',
  idealRADARVehicle1AccelerationY = 'idealRADARVehicle1AccelerationY',
  idealRADARVehicle1AccelerationZ = 'idealRADARVehicle1AccelerationZ',
  idealRADARVehicle1RelativeDistanceX = 'idealRADARVehicle1RelativeDistanceX',
  idealRADARVehicle1RelativeDistanceY = 'idealRADARVehicle1RelativeDistanceY',
  idealRADARVehicle1RelativeVelocityX = 'idealRADARVehicle1RelativeVelocityX',
  idealRADARVehicle1RelativeVelocityY = 'idealRADARVehicle1RelativeVelocityY',
  idealRADARVehicle1RelativeAccelerationX = 'idealRADARVehicle1RelativeAccelerationX',
  idealRADARVehicle1RelativeAccelerationY = 'idealRADARVehicle1RelativeAccelerationY',
  idealRADARVehicle2Distance = 'idealRADARVehicle2Distance',
  idealRADARVehicle2Length = 'idealRADARVehicle2Length',
  idealRADARVehicle2Width = 'idealRADARVehicle2Width',
  idealRADARVehicle2VelocityX = 'idealRADARVehicle2VelocityX',
  idealRADARVehicle2VelocityY = 'idealRADARVehicle2VelocityY',
  idealRADARVehicle2VelocityZ = 'idealRADARVehicle2VelocityZ',
  idealRADARVehicle2AccelerationX = 'idealRADARVehicle2AccelerationX',
  idealRADARVehicle2AccelerationY = 'idealRADARVehicle2AccelerationY',
  idealRADARVehicle2AccelerationZ = 'idealRADARVehicle2AccelerationZ',
  idealRADARVehicle2RelativeDistanceX = 'idealRADARVehicle2RelativeDistanceX',
  idealRADARVehicle2RelativeDistanceY = 'idealRADARVehicle2RelativeDistanceY',
  idealRADARVehicle2RelativeVelocityX = 'idealRADARVehicle2RelativeVelocityX',
  idealRADARVehicle2RelativeVelocityY = 'idealRADARVehicle2RelativeVelocityY',
  idealRADARVehicle2RelativeAccelerationX = 'idealRADARVehicle2RelativeAccelerationX',
  idealRADARVehicle2RelativeAccelerationY = 'idealRADARVehicle2RelativeAccelerationY',
  idealRADARVehicle3Distance = 'idealRADARVehicle3Distance',
  idealRADARVehicle3Length = 'idealRADARVehicle3Length',
  idealRADARVehicle3Width = 'idealRADARVehicle3Width',
  idealRADARVehicle3VelocityX = 'idealRADARVehicle3VelocityX',
  idealRADARVehicle3VelocityY = 'idealRADARVehicle3VelocityY',
  idealRADARVehicle3VelocityZ = 'idealRADARVehicle3VelocityZ',
  idealRADARVehicle3AccelerationX = 'idealRADARVehicle3AccelerationX',
  idealRADARVehicle3AccelerationY = 'idealRADARVehicle3AccelerationY',
  idealRADARVehicle3AccelerationZ = 'idealRADARVehicle3AccelerationZ',
  idealRADARVehicle3RelativeDistanceX = 'idealRADARVehicle3RelativeDistanceX',
  idealRADARVehicle3RelativeDistanceY = 'idealRADARVehicle3RelativeDistanceY',
  idealRADARVehicle3RelativeVelocityX = 'idealRADARVehicle3RelativeVelocityX',
  idealRADARVehicle3RelativeVelocityY = 'idealRADARVehicle3RelativeVelocityY',
  idealRADARVehicle3RelativeAccelerationX = 'idealRADARVehicle3RelativeAccelerationX',
  idealRADARVehicle3RelativeAccelerationY = 'idealRADARVehicle3RelativeAccelerationY',
  idealRADARVehicle4Distance = 'idealRADARVehicle4Distance',
  idealRADARVehicle4Length = 'idealRADARVehicle4Length',
  idealRADARVehicle4Width = 'idealRADARVehicle4Width',
  idealRADARVehicle4VelocityX = 'idealRADARVehicle4VelocityX',
  idealRADARVehicle4VelocityY = 'idealRADARVehicle4VelocityY',
  idealRADARVehicle4VelocityZ = 'idealRADARVehicle4VelocityZ',
  idealRADARVehicle4AccelerationX = 'idealRADARVehicle4AccelerationX',
  idealRADARVehicle4AccelerationY = 'idealRADARVehicle4AccelerationY',
  idealRADARVehicle4AccelerationZ = 'idealRADARVehicle4AccelerationZ',
  idealRADARVehicle4RelativeDistanceX = 'idealRADARVehicle4RelativeDistanceX',
  idealRADARVehicle4RelativeDistanceY = 'idealRADARVehicle4RelativeDistanceY',
  idealRADARVehicle4RelativeVelocityX = 'idealRADARVehicle4RelativeVelocityX',
  idealRADARVehicle4RelativeVelocityY = 'idealRADARVehicle4RelativeVelocityY',
  idealRADARVehicle4RelativeAccelerationX = 'idealRADARVehicle4RelativeAccelerationX',
  idealRADARVehicle4RelativeAccelerationY = 'idealRADARVehicle4RelativeAccelerationY',

  roadsRoadHalfWidth = 'roadsRoadHalfWidth',                                                        -- Roads sensor.
  roadsRoadRadius = 'roadsRoadRadius',
  roadsRoadHeading = 'roadsRoadHeading',
  roadsDistanceToCenterline = 'roadsDistanceToCenterline',
  roadsDistanceToRoadLeftEdge = 'roadsDistanceToRoadLeftEdge',
  roadsDistanceToRoadRightEdge = 'roadsDistanceToRoadRightEdge',
  roadsDrivability = 'roadsDrivability',
  roadsSpeedLimit = 'roadsSpeedLimit',
  roadsIsOneWay = 'roadsIsOneWay',
  roadsClosestPointX = 'roadsClosestPointX',
  roadsClosestPointY = 'roadsClosestPointY',
  roadsClosestPointZ = 'roadsClosestPointZ',
  roads2ndClosestPointX = 'roads2ndClosestPointX',
  roads2ndClosestPointY = 'roads2ndClosestPointY',
  roads2ndClosestPointZ = 'roads2ndClosestPointZ',
  roads3rdClosestPointX = 'roads3rdClosestPointX',
  roads3rdClosestPointY = 'roads3rdClosestPointY',
  roads3rdClosestPointZ = 'roads3rdClosestPointZ',
  roads4thClosestPointX = 'roads4thClosestPointX',
  roads4thClosestPointY = 'roads4thClosestPointY',
  roads4thClosestPointZ = 'roads4thClosestPointZ',
  roadsReadingTimestamp = 'roadsReadingTimestamp' }


-- Public interface.
M.headers =                                               headers
M.groups =                                                groups
M.names =                                                 names

return M